name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ] # Déclenche la pipeline dès qu'on pousse sur 'main'

jobs:
  deploy-infrastructure:
    runs-on: self-hosted # Utilise ton runner local

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Builder l'image Docker
        run: |
          # ÉTAPE CRUCIALE : On se déplace dans le dossier prt1 avant de build
          cd prt1 
          
          # On build l'image en utilisant le contexte du dossier de l'API
          sudo docker build -t hamustra/api-lacets:latest .
          
          # On injecte l'image dans K3s (pas besoin de cd ici, l'image est déjà dans Docker)
          sudo docker save hamustra/api-lacets:latest | sudo k3s ctr images import -

      - name: Déployer sur l'infrastructure Kubernetes
        run: |
          # On précise le chemin vers le fichier de config qui est maintenant dans prt1
          sudo k3s kubectl apply -f prt1/api-config.yaml
          
          # On force le redémarrage pour appliquer la nouvelle image
          sudo k3s kubectl rollout restart deployment/api-server